### ISSUE TITLE
could that make two splace at line end automatic 

### ISSUE THREAD

**Issue by iczrac** [deathau/cm-show-whitespace-obsidian#7]

**Comment by jjspace** [comment]
Can you please expand on what you're requesting?

* Are you expecting something to happen when you type two spaces at the end of a line? Like automatically insert a newline character? If so that's likely outside the scope of this plugin
* Are you expecting two spaces to be inserted at the end of every line automatically? If it's this one that's again outside the scope of showing spaces, you should look for a formatter.

If neither of those are what you're looking for then please explain!

**Comment by iczrac** [comment]
Thanks for your reply，I am  expecting that an option for  inserting  two spaces at the end of every line automatically for every Markdown file

**Comment by deathau** [comment]
@iczrac, yeah, I think that's out of scope for this plugin, which only aims to _show_ the whitespace. It's probably worth making a request on the Obsidian forums
